services:
  backend-dev:
    image: ghcr.io/nstafford/pocus-health-backend:dev
    restart: unless-stopped
    container_name: pocus-backend-dev
    environment:
      - PORT=8000
    networks:
      - default

networks:
  default:
    name: pocus-health_default
    external: true
